name: Deploy doc
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v6
                with:
                    ref: main
            -   uses: oven-sh/setup-bun@v2
            -   run: bun install

            -   name: Build
                run: bun run doc:build

            -   name: Deploy
                uses: peaceiris/actions-gh-pages@v4
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    publish_dir: ./docs/.vitepress/dist
